import { AgentEvent, type AgentExecutor, type ExecutionEventBus, type RequestContext } from '@a2a-js/sdk/server';
import {
  Role,
  TaskState,
  type Artifact,
  type Task,
  type TaskArtifactUpdateEvent,
  type TaskStatusUpdateEvent,
} from '@a2a-js/sdk';
import { randomUUID } from 'node:crypto';

import { agentMessage, extractMessageText, textPart } from './a2a-helpers.js';
import type { LangGraphAgent } from './server-agent.js';

/**
 * 将 LangGraph Server Agent 适配为官方 A2A SDK 的任务执行器。
 */
export class LangGraphAgentExecutor implements AgentExecutor {
  private readonly activeExecutions = new Map<string, { controller: AbortController; contextId: string }>();

  /**
   * 创建执行器并持有用于生成回答的 Server Agent。
   *
   * @param agent - 处理用户文本请求的 LangGraph Server Agent。
   */
  constructor(private readonly agent: LangGraphAgent) {}

  /**
   * 执行一个 A2A 任务，并按 submitted、working、artifact、completed 生命周期发布事件。
   *
   * @param context - SDK 提供的任务、会话和用户消息上下文。
   * @param eventBus - 用于发布 A2A 任务状态和产物事件的事件总线。
   * @returns 任务完成、拒绝或被取消后结束。
   */
  execute = async (context: RequestContext, eventBus: ExecutionEventBus): Promise<void> => {
    const { taskId, contextId, userMessage } = context;
    const controller = new AbortController();
    this.activeExecutions.set(taskId, { controller, contextId });

    // 新任务需要先发布 submitted 状态；已有任务则复用 SDK 传入的任务对象。
    const initialTask: Task = context.task ?? {
      id: taskId,
      contextId,
      status: {
        state: TaskState.TASK_STATE_SUBMITTED,
        timestamp: new Date().toISOString(),
        message: undefined,
      },
      artifacts: [],
      history: [userMessage],
      metadata: userMessage.metadata ?? {},
    };
    eventBus.publish(AgentEvent.task(initialTask));

    // 在调用模型前通知 Client，便于其展示“处理中”状态。
    const workingUpdate: TaskStatusUpdateEvent = {
      taskId,
      contextId,
      status: {
        state: TaskState.TASK_STATE_WORKING,
        timestamp: new Date().toISOString(),
        message: agentMessage('LangGraph is processing the request.', taskId, contextId),
      },
      metadata: {},
    };
    eventBus.publish(AgentEvent.statusUpdate(workingUpdate));

    try {
      // A2A 当前仅接受非空文本 Part，其他内容类型会被拒绝。
      const prompt = extractMessageText(userMessage).trim();
      if (!prompt) {
        eventBus.publish(
          AgentEvent.statusUpdate({
            taskId,
            contextId,
            status: {
              state: TaskState.TASK_STATE_REJECTED,
              timestamp: new Date().toISOString(),
              message: agentMessage('A non-empty text prompt is required.', taskId, contextId),
            },
            metadata: {},
          }),
        );
        return;
      }

      // 将 AbortController 透传给 LangGraph，支持 cancelTask 中断模型执行。
      const response = await this.agent.respond(prompt, contextId, controller.signal);
      if (controller.signal.aborted) return;

      // 先以 artifact 形式发布完整回答，再以 completed 状态结束任务。
      const artifact: Artifact = {
        artifactId: randomUUID(),
        name: 'assistant_response',
        description: 'Final response generated by LangGraph.',
        parts: [textPart(response)],
        metadata: undefined,
        extensions: [],
      };
      const artifactUpdate: TaskArtifactUpdateEvent = {
        taskId,
        contextId,
        artifact,
        append: false,
        lastChunk: true,
        metadata: undefined,
      };
      eventBus.publish(AgentEvent.artifactUpdate(artifactUpdate));
      eventBus.publish(
        AgentEvent.statusUpdate({
          taskId,
          contextId,
          status: {
            state: TaskState.TASK_STATE_COMPLETED,
            timestamp: new Date().toISOString(),
            message: {
              messageId: randomUUID(),
              role: Role.ROLE_AGENT,
              parts: [textPart(response)],
              taskId,
              contextId,
              extensions: [],
              metadata: {},
              referenceTaskIds: [],
            },
          },
          metadata: undefined,
        }),
      );
    } catch (error) {
      if (!controller.signal.aborted) throw error;
    } finally {
      // 无论成功、拒绝或取消都清理运行中的控制器，避免内存泄漏。
      this.activeExecutions.delete(taskId);
    }
  };

  /**
   * 取消正在运行的 A2A 任务，并向 Client 发布 canceled 状态。
   *
   * @param taskId - 要取消的 A2A 任务标识。
   * @param eventBus - 用于发布任务取消状态的事件总线。
   * @returns 取消信号已发送且状态事件已发布后结束。
   */
  cancelTask = async (taskId: string, eventBus: ExecutionEventBus): Promise<void> => {
    const execution = this.activeExecutions.get(taskId);
    // AbortController 会让仍在执行的 LangGraph 请求尽快停止。
    execution?.controller.abort();
    eventBus.publish(
      AgentEvent.statusUpdate({
        taskId,
        contextId: execution?.contextId ?? '',
        status: {
          state: TaskState.TASK_STATE_CANCELED,
          timestamp: new Date().toISOString(),
          message: undefined,
        },
        metadata: undefined,
      }),
    );
  };
}
